name: "Rich Navigation Indexing"
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  richnav:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2.4.0
      with: 
        java-version: '11'
        distribution: 'microsoft'
    - uses: microsoft/RichCodeNavIndexer@v0.1
      with:
        languages: 'csharp,typescript,java,cpp'
        environment: 'development'
      continue-on-error: true
